[pytest]
disable_plugins =
    launch_testing_ros_pytest_entrypoint
    launch_testing
    launch_testing_ros
    ament_lint
    ament_pep257
    ament_copyright
    ament_xmllint
    ament_flake8
    colcon_core
